// <auto-generated />
using System;
using DatabaseDistributedLock;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseDistributedLock.Migrations
{
    [DbContext(typeof(LockDbContext))]
    partial class LockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DatabaseDistributedLock.LockRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("Count")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpireTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Key");

                    b.ToTable("lock_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
